version: "2" # using 2 because 3 doesn't support extending

services:
  e2e-cypress:
    build:
      context: ./e2e/
      dockerfile: Dockerfile
    # command: 'cypress run --browser chrome'
    container_name: e2e-tr
    depends_on:
      - tvrenamer_prod
    environment:
      CYPRESS_baseUrl: http://host.docker.internal:3000
      # ELECTRON_ENABLE_LOGGING: 1 # view console logs from Browser (headless)
      # DEBUG: cypress:server:browsers:electron # view Electron internal logging
      DIST_FILES_PATH: /dist
      MOCK_FILES_PATH: /e2e/mnt/mockFiles
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ports:
      - "9001:3000"
    working_dir: /e2e
    volumes:
      - "${PWD}/e2e:/e2e"
      - "${PWD}/dist:/dist"
  
  tv-renamer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tv-renamer
    environment:
      NODE_ENV: production
      TZ: America/Los_Angeles
    image: theonewhoknocks/tv-renamer
    ports:
      # map Local port to the containers exposed port
      - "3000:3000"
    volumes:
      # Map shell files over, so they're maintained between sessions
      - "${PWD}/.docker/.vimrc:/root/.vimrc"
      - "${PWD}/.docker/.zshrc:/root/.zshrc"
      - "${PWD}/.ignore/.zsh_history:/root/.zsh_history"
      # Map media sources
      - "${PWD}/e2e/mnt/mockFiles:/media/files"
  
  tvrenamer_prod:
    container_name: tvrenamer_prod
    environment:
      DATA_PATH: ./data
      DISABLE_LOGS: 'true'
    extends: tv-renamer # allows for just changing key pieces of data for development
    volumes:
      # NOTE - To ensure data doesn't get wiped during a `purge`, using a
      # bind-mount.
      - "${PWD}/e2e/mnt/data:/home/node/app/data"
  
  tvrenamer_dev:
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: tvrenamer_dev
    environment:
      DATA_PATH: ../e2e/mnt/data
      NODE_ENV: development
    extends: tv-renamer # allows for just changing key pieces of data for development
    ports:
      # browserSync
      - "3001:3001" 
      - "3002:3002"
      - "3003:3003"
      # inspector
      - "9229:9229"
    volumes:
      # Map the current directory over so I can Dev in an env that has ffmpeg
      - "${PWD}:/home/node/app"
