version: "3.4"

services:
  e2e-cypress:
    container_name: e2e-tr
    depends_on:
      - tv-renamer
    environment:
      CYPRESS_baseUrl: http://host.docker.internal:9000
    image: cypress/included:4.12.1
    ports:
      - "9001:3000"
    working_dir: /e2e
    volumes:
      - "${PWD}/e2e:/e2e"
      - "${PWD}/bin/files.txt:/mockData/files.txt"
  
  tv-renamer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tv-renamer
    environment:
      NODE_ENV: production
    image: theonewhoknocks/tv-renamer
    ports:
      # The local port of 9000 will map to the containers exposed port 3001
      - "9000:3001"
    volumes:
      # NOTE - To ensure data doesn't get wiped during a `purge`, using a
      # bind-mount. While in Dev, Node maps to `dist/.data`, but when testing in
      # Docker you'll have to copy that `.data` folder into `.ignore/` and then
      # update `sourceFolder` & `outputFolder` in `.ignore/.data/config.json`
      # to point to `/home/node/app/_temp_`.
      - "${PWD}/.ignore/.data:/home/node/app/.data"
      # For testing purposes, using a bind-mount which is pointing to the
      # current repo's `.ignore/tmp` directory and mapping it to
      # `/home/node/app/_temp_`.
      - "${PWD}/.ignore/tmp:/home/node/app/_temp_"
