version: "3.4"

services:
  e2e-cypress:
    container_name: e2e-tr
    depends_on:
      - tv-renamer
    environment:
      CYPRESS_baseUrl: http://host.docker.internal:9000
    image: cypress/included:5.1.0
    ipc: host # https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    ports:
      - "9001:3000"
    working_dir: /e2e
    volumes:
      - "${PWD}/e2e:/e2e"
      - "${PWD}/e2e/bin/files.txt:/mockData/files.txt"
  
  tv-renamer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tv-renamer
    environment:
      NODE_ENV: production
    image: theonewhoknocks/tv-renamer
    ports:
      # The local port of 9000 will map to the containers exposed port 3001
      - "9000:3001"
    volumes:
      # NOTE - To ensure data doesn't get wiped during a `purge`, using a
      # bind-mount.
      - "${PWD}/e2e/mnt/data:/home/node/app/.data"
      # The config points to `_temp_` for source and output folders
      - "${PWD}/e2e/mnt/mockFiles:/home/node/app/_temp_"
